// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"database/sql"
	"time"
)

type Attendance struct {
	ID        int32     `db:"id" json:"id"`
	StudentID int32     `db:"student_id" json:"studentId"`
	CourseID  int32     `db:"course_id" json:"courseId"`
	CollegeID int32     `db:"college_id" json:"collegeId"`
	LectureID int32     `db:"lecture_id" json:"lectureId"`
	Date      time.Time `db:"date" json:"date"`
	Status    string    `db:"status" json:"status"`
	ScannedAt time.Time `db:"scanned_at" json:"scannedAt"`
	CreatedAt time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt time.Time `db:"updated_at" json:"updatedAt"`
}

type College struct {
	ID        int32          `db:"id" json:"id"`
	Name      string         `db:"name" json:"name"`
	Address   sql.NullString `db:"address" json:"address"`
	City      sql.NullString `db:"city" json:"city"`
	State     sql.NullString `db:"state" json:"state"`
	Country   sql.NullString `db:"country" json:"country"`
	CreatedAt time.Time      `db:"created_at" json:"createdAt"`
	UpdatedAt time.Time      `db:"updated_at" json:"updatedAt"`
}

type Course struct {
	ID           int32          `db:"id" json:"id"`
	Name         string         `db:"name" json:"name"`
	Description  sql.NullString `db:"description" json:"description"`
	Credits      int32          `db:"credits" json:"credits"`
	InstructorID sql.NullInt32  `db:"instructor_id" json:"instructorId"`
	CreatedAt    time.Time      `db:"created_at" json:"createdAt"`
	UpdatedAt    time.Time      `db:"updated_at" json:"updatedAt"`
}

type Enrollment struct {
	ID             int32          `db:"id" json:"id"`
	StudentID      int32          `db:"student_id" json:"studentId"`
	CourseID       int32          `db:"course_id" json:"courseId"`
	CollegeID      int32          `db:"college_id" json:"collegeId"`
	EnrollmentDate time.Time      `db:"enrollment_date" json:"enrollmentDate"`
	Status         string         `db:"status" json:"status"`
	Grade          sql.NullString `db:"grade" json:"grade"`
	CreatedAt      time.Time      `db:"created_at" json:"createdAt"`
	UpdatedAt      time.Time      `db:"updated_at" json:"updatedAt"`
}

type Lecture struct {
	ID              int32          `db:"id" json:"id"`
	CollegeID       int32          `db:"college_id" json:"collegeId"`
	CourseID        int32          `db:"course_id" json:"courseId"`
	LectureDatetime time.Time      `db:"lecture_datetime" json:"lectureDatetime"`
	Topic           sql.NullString `db:"topic" json:"topic"`
	CreatedAt       time.Time      `db:"created_at" json:"createdAt"`
	UpdatedAt       time.Time      `db:"updated_at" json:"updatedAt"`
}

type Qrcode struct {
	ID        int32     `db:"id" json:"id"`
	StudentID int32     `db:"student_id" json:"studentId"`
	QrCodeID  string    `db:"qr_code_id" json:"qrCodeId"`
	IssuedAt  time.Time `db:"issued_at" json:"issuedAt"`
	ExpiresAt time.Time `db:"expires_at" json:"expiresAt"`
	IsActive  bool      `db:"is_active" json:"isActive"`
	CreatedAt time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt time.Time `db:"updated_at" json:"updatedAt"`
}

type Student struct {
	StudentID        int32         `db:"student_id" json:"studentId"`
	UserID           int32         `db:"user_id" json:"userId"`
	CollegeID        int32         `db:"college_id" json:"collegeId"`
	KratosIdentityID string        `db:"kratos_identity_id" json:"kratosIdentityId"`
	EnrollmentYear   sql.NullInt32 `db:"enrollment_year" json:"enrollmentYear"`
	RollNo           string        `db:"roll_no" json:"rollNo"`
	IsActive         bool          `db:"is_active" json:"isActive"`
	CreatedAt        time.Time     `db:"created_at" json:"createdAt"`
	UpdatedAt        time.Time     `db:"updated_at" json:"updatedAt"`
}

type User struct {
	ID               int32     `db:"id" json:"id"`
	KratosIdentityID string    `db:"kratos_identity_id" json:"kratosIdentityId"`
	Name             string    `db:"name" json:"name"`
	Role             string    `db:"role" json:"role"`
	Email            string    `db:"email" json:"email"`
	IsActive         bool      `db:"is_active" json:"isActive"`
	CreatedAt        time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt        time.Time `db:"updated_at" json:"updatedAt"`
}
