// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"context"
)

type Querier interface {
	FreezeAttendance(ctx context.Context, arg FreezeAttendanceParams) error
	GetAttendanceByCourse(ctx context.Context, arg GetAttendanceByCourseParams) ([]GetAttendanceByCourseRow, error)
	GetAttendanceByLecture(ctx context.Context, arg GetAttendanceByLectureParams) ([]GetAttendanceByLectureRow, error)
	GetAttendanceStudent(ctx context.Context, arg GetAttendanceStudentParams) ([]GetAttendanceStudentRow, error)
	GetAttendanceStudentInCourse(ctx context.Context, arg GetAttendanceStudentInCourseParams) ([]GetAttendanceStudentInCourseRow, error)
	MarkAttendance(ctx context.Context, arg MarkAttendanceParams) (Attendance, error)
	SetAttendanceStatus(ctx context.Context, arg SetAttendanceStatusParams) error
	UnFreezeAttendance(ctx context.Context, arg UnFreezeAttendanceParams) error
	UpdateAttendance(ctx context.Context, arg UpdateAttendanceParams) error
}

var _ Querier = (*Queries)(nil)
