ALTER TABLE user_settings 
ADD COLUMN IF NOT EXISTS assignment_reminders BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS grade_updates BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS announcement_alerts BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS timezone VARCHAR(50) DEFAULT 'UTC',
ADD COLUMN IF NOT EXISTS session_timeout INTEGER DEFAULT 30;
