basePath: /
host: localhost:8080 // Change if needed
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: API for the EduHub platform.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: EduHub API
  version: "1.0"
paths:
  /docs:
    get:
      consumes:
      - application/json
      description: Access the Swagger documentation
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: API Documentation
      tags:
      - system
  /health:
    get:
      consumes:
      - application/json
      description: Get server health status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Health check endpoint
      tags:
      - system
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization // Or X-Session-Token depending on your auth mechanism
    type: apiKey
swagger: "2.0"
