// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountCoursesByCollege(ctx context.Context, collegeID sql.NullInt32) (int64, error)
	CountCoursesByInstructor(ctx context.Context, arg CountCoursesByInstructorParams) (int64, error)
	CountStudentsByCollege(ctx context.Context, collegeID int32) (int64, error)
	CreateCourse(ctx context.Context, arg CreateCourseParams) (CreateCourseRow, error)
	CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error)
	DeleteCourse(ctx context.Context, arg DeleteCourseParams) error
	DeleteStudent(ctx context.Context, arg DeleteStudentParams) error
	FindAllCourses(ctx context.Context, arg FindAllCoursesParams) ([]FindAllCoursesRow, error)
	FindAllStudentsByCollege(ctx context.Context, arg FindAllStudentsByCollegeParams) ([]Student, error)
	FindByKratosID(ctx context.Context, kratosIdentityID string) (Student, error)
	FindCourseByID(ctx context.Context, arg FindCourseByIDParams) (FindCourseByIDRow, error)
	FindCoursesByInstructor(ctx context.Context, arg FindCoursesByInstructorParams) ([]FindCoursesByInstructorRow, error)
	FreezeAttendance(ctx context.Context, arg FreezeAttendanceParams) error
	FreezeStudent(ctx context.Context, rollNo string) error
	GetAttendanceByCourse(ctx context.Context, arg GetAttendanceByCourseParams) ([]GetAttendanceByCourseRow, error)
	GetAttendanceByLecture(ctx context.Context, arg GetAttendanceByLectureParams) ([]GetAttendanceByLectureRow, error)
	GetAttendanceStudent(ctx context.Context, arg GetAttendanceStudentParams) ([]GetAttendanceStudentRow, error)
	GetAttendanceStudentInCourse(ctx context.Context, arg GetAttendanceStudentInCourseParams) ([]GetAttendanceStudentInCourseRow, error)
	GetStudentByID(ctx context.Context, arg GetStudentByIDParams) (Student, error)
	GetStudentByRollNo(ctx context.Context, arg GetStudentByRollNoParams) (Student, error)
	MarkAttendance(ctx context.Context, arg MarkAttendanceParams) (Attendance, error)
	SetAttendanceStatus(ctx context.Context, arg SetAttendanceStatusParams) error
	UnFreezeAttendance(ctx context.Context, arg UnFreezeAttendanceParams) error
	UnFreezeStudent(ctx context.Context, rollNo string) error
	UpdateAttendance(ctx context.Context, arg UpdateAttendanceParams) error
	UpdateCourse(ctx context.Context, arg UpdateCourseParams) error
	UpdateStudent(ctx context.Context, arg UpdateStudentParams) error
}

var _ Querier = (*Queries)(nil)
